author: lvgo
title: Star Dust 星尘
description: 专注 Java 技术、并发编程、网络编程、大数据方向相关内容研究。
keyword: lvgo star dust
favicon: ../images/L.png
logo: /images/L.png

language: zh-CN
#excerpt_link: Read more

menu:
  首页: /
  标签: /tags/
  归档: /archives/
  开源项目: /project/
# About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# 要饭模式
#donate: true

# share qrcode
#qrcode: true

# comment
# you can set gitment, uyan or disqus gitalk

comment: gitalk


# gitalk config
gitalk:
  ClientID: c85c431dec5b3fa75527
  ClientSecret: f5f4199617efe01a998333307bb1008a09b4a2d7
  repo: gitalk
  owner: lvgocc
  adminUser: lvgocc
  pagerDirection: last
  distractionFreeMode: true

# gitment config
gitment_owner:
gitment_repo:
gitment_oauth_id:
gitment_oauth_secret:

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: code-jxb3G2xK9c
google_analytics: sV9GoccAvPsX-CXyXEeaUzDEvk4d77Ca-eoFKT5-2RM
# disqus config
disqus_shortname:

about:
  banner: ../images/rmch2.jpg
  avatar: ../images/L.png
  description: "The end is always near."
  #  weibo_username:
  #  twitter_username:
  github_username: lvgocc
#  zhihu_username:
#  douban_username:
#  linkedin_username:

# MathJax Support
mathjax:
  enable: false
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# image
zoom:
  enable: false

FancyBox:
  enable: true

cdn:
  js:
    fastclick: //lib.baomitu.com/fastclick/1.0.6/fastclick.min.js
    highlight: //lib.baomitu.com/highlight.js/9.15.10/highlight.min.js
    jquery: //lib.baomitu.com/jquery/3.5.0/jquery.min.js
    geopattern: //lib.baomitu.com/geopattern/1.2.3/js/geopattern.min.js
    nprogress: //lib.baomitu.com/nprogress/0.2.0/nprogress.min.js
    gitalk: //lib.baomitu.com/gitalk/1.6.2/gitalk.min.js
  css:
    gitalk: //lib.baomitu.com/gitalk/1.6.2/gitalk.min.css
    fontawesome: //lib.baomitu.com/font-awesome/4.7.0/css/font-awesome.min.css
    nprogress: //lib.baomitu.com/nprogress/0.2.0/nprogress.min.css
